update

# Search old versions
tap 'homebrew/versions' || true

install zsh
install emacs
install cask || upgrade cask
install coreutils || true
install binutils || true
install rbenv ruby-build || true
install git || true
install scala sbt || true

# homebrew-cask
tap 'caskroom/cask' || true
tap 'caskroom/versions' || true
install brew-cask

cask install java java7
cask install flash adobe-reader
cask install skim
